\echo Use "CREATE EXTENSION char_count" to load this file. \quit
CREATE FUNCTION char_count(TEXT, TEXT)
RETURNS INTEGER
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION print_count(INT)
RETURNS INTEGER
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT;